### ISSUE TITLE
Can't open example @ Mac

### ISSUE THREAD

**Issue by yayscripting** [arturadib/node-qt#5] opened 2012-04-10 15:06 UTC
I am getting the following result when I try to run the tests. I built it via NPM. v0.6.15 (Mac). The same results appear when I run an example.

`````` bash
$ node make test
_________________________________________________________________
Running Node-Qt tests

rm: no such file or directory: img-test/*

Running test file qcolor.js
Running test file qfont.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
Running test file qimage.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
Running test file qmatrix.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
Running test file qpainter.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
Running test file qpainterpath.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
Running test file qpen.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
Running test file qpixmap.js
Running test file qpointf.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
Running test file qscrollarea.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
Running test file qsound.js

node.js:201
Running test file qwidget.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/myusername/nodeApps/node_modules/node-qt/build/Release/qt.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)```
``````

**Comment by arturadib** [comment] 2012-04-10 17:23
hi, thanks for reporting this. was the build successful? i.e. did you get this:

```
spawn make [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/qt/src/qt.o
  CXX(target) Release/obj.target/qt/src/QtCore/qsize.o
  CXX(target) Release/obj.target/qt/src/QtCore/qpointf.o
  CXX(target) Release/obj.target/qt/src/QtGui/qapplication.o
  CXX(target) Release/obj.target/qt/src/QtGui/qwidget.o
  CXX(target) Release/obj.target/qt/src/QtGui/qmouseevent.o
  CXX(target) Release/obj.target/qt/src/QtGui/qkeyevent.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpixmap.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpainter.o
  CXX(target) Release/obj.target/qt/src/QtGui/qcolor.o
  CXX(target) Release/obj.target/qt/src/QtGui/qbrush.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpen.o
  CXX(target) Release/obj.target/qt/src/QtGui/qimage.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpainterpath.o
  CXX(target) Release/obj.target/qt/src/QtGui/qfont.o
  CXX(target) Release/obj.target/qt/src/QtGui/qmatrix.o
  CXX(target) Release/obj.target/qt/src/QtGui/qsound.o
  CXX(target) Release/obj.target/qt/src/QtGui/qscrollarea.o
  CXX(target) Release/obj.target/qt/src/QtGui/qscrollbar.o
  CXX(target) Release/obj.target/qt/src/QtTest/qtesteventlist.o
  SOLINK_MODULE(target) Release/qt.node
  SOLINK_MODULE(target) Release/qt.node: Finished
info done ok 
```

also I wonder if it could be a Mac version issue. what Mac version are you using?

**Comment by TooTallNate** [comment] 2012-04-10 17:24
@yayscripting Try node v0.7.7 and it will give you a more helpful error message than "Unable to load shared library"

**Comment by yayscripting** [comment] 2012-04-10 17:49
This is the result of the total build process:

``` bash
$ git clone git://github.com/arturadib/node-qt.git

Cloning into node-qt...
remote: Counting objects: 3912, done.
remote: Compressing objects: 100% (1675/1675), done.
remote: Total 3912 (delta 1087), reused 3894 (delta 1069)
Receiving objects: 100% (3912/3912), 14.54 MiB | 363 KiB/s, done.
Resolving deltas: 100% (1087/1087), done.

$ cd node-qt
$ npm install

npm http GET https://registry.npmjs.org/shelljs/0.0.5pre4
npm http 304 https://registry.npmjs.org/shelljs/0.0.5pre4

> node-qt@0.0.2 install /Users/myusername/nodeApps/node-qt
> node-gyp rebuild

info it worked if it ends with ok 
spawn python [ '/Users/myusername/.node-gyp/0.6.15/tools/gyp_addon',
  'binding.gyp',
  '-I/Users/myusername/nodeApps/node-qt/build/config.gypi',
  '-f',
  'make' ]
spawn make [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/qt/src/qt.o
  CXX(target) Release/obj.target/qt/src/QtCore/qsize.o
  CXX(target) Release/obj.target/qt/src/QtCore/qpointf.o
  CXX(target) Release/obj.target/qt/src/QtGui/qapplication.o
  CXX(target) Release/obj.target/qt/src/QtGui/qwidget.o
  CXX(target) Release/obj.target/qt/src/QtGui/qmouseevent.o
  CXX(target) Release/obj.target/qt/src/QtGui/qkeyevent.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpixmap.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpainter.o
  CXX(target) Release/obj.target/qt/src/QtGui/qcolor.o
  CXX(target) Release/obj.target/qt/src/QtGui/qbrush.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpen.o
  CXX(target) Release/obj.target/qt/src/QtGui/qimage.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpainterpath.o
  CXX(target) Release/obj.target/qt/src/QtGui/qfont.o
  CXX(target) Release/obj.target/qt/src/QtGui/qmatrix.o
  CXX(target) Release/obj.target/qt/src/QtGui/qsound.o
  CXX(target) Release/obj.target/qt/src/QtGui/qscrollarea.o
  CXX(target) Release/obj.target/qt/src/QtGui/qscrollbar.o
  CXX(target) Release/obj.target/qt/src/QtTest/qtesteventlist.o
  SOLINK_MODULE(target) Release/qt.node
  SOLINK_MODULE(target) Release/qt.node: Finished
info done ok 
shelljs@0.0.5pre4 ./node_modules/shelljs
```

I'm currently using Mac OS X Snow Leopard 10.6.8. I'll try node v0.7.7 to get a more helpful error message.

**Comment by yayscripting** [comment] 2012-04-10 18:12
I installed a newer version of node and I am indeed getting a better error message:

``` bash
$ node -v
v0.7.8-pre

$ cd ~/nodeApps/node-qt/examples; node helloworld.js

node.js:247
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: dlopen(/Users/myusername/nodeApps/node-qt/build/Release/qt.node, 1): Library not loaded: /usr/X11/lib/libpng15.15.dylib
  Referenced from: /Users/myusername/nodeApps/node-qt/deps/qt-4.8.0/darwin/x64/lib/QtGui.framework/QtGui
  Reason: image not found
    at Object..node (module.js:475:11)
    at Module.load (module.js:351:32)
    at Function._load (module.js:309:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/myusername/nodeApps/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:444:26)
    at Object..js (module.js:462:10)
    at Module.load (module.js:351:32)
    at Function._load (module.js:309:12)
```

My guess is that my version of Mac OS X is missing a framework?

**Comment by yayscripting** [comment] 2012-04-10 18:15
I would like to point out another conversation I found which looks like our problem: https://github.com/mxcl/homebrew/issues/11234

> This is a good point. Even though X11 is "standard" since Leopard, there is still an option to switch it off and the upcoming Mountain Lion release won't include X11 components by default. Because of this, it is wise to copy all external dylibs into the app bundle.
> 
> For example, the CMake Qt bundling scripts, which Mike wrote, will copy anything that is not in /usr/lib or /System/Frameworks (if I recall correctly).

**Comment by arturadib** [comment] 2012-04-10 18:21
the binaries in deps/qt-4.8.0 were built on Lion, maybe that's the
problem. I'll need to look into this further, somehow. maybe I'll get
a Snow Leopard on my VMWare.

**Comment by TooTallNate** [comment] 2012-04-10 18:23
@arturadib the problem is in his error messages from v0.7.7: "not found: /usr/X11/lib/libpng15.15.dylib"

So maybe you'll need to start bundling libpng as well?

**Comment by yayscripting** [comment] 2012-04-10 18:24
The guy in my quote suggests to 'copy all external dylibs into the app bundle'.

**Comment by arturadib** [comment] 2012-04-10 21:17
@yayscripting @TooTallNate typing `$ otool -L QtGui` gives:

```
    lib/QtGui.framework/QtGui (compatibility version 4.8.0, current version 4.8.0)
    lib/QtCore.framework/QtCore (compatibility version 4.8.0, current version 4.8.0)
    /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 153.0.0)
    /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
    /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1138.23.0)
    /usr/X11/lib/libpng15.15.dylib (compatibility version 20.0.0, current version 20.0.0)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 52.0.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1094.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
    /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
    /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 53.0.0)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 635.15.0)
    /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 41.0.0)
    /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 833.20.0)
```

from the quote above it seems like `/usr/lib/*` and `/System/Library/*` dependencies are all standard; everything else needs to be bundled.

@yayscripting can you please download my `libpng` into `/usr/X11/lib/libpng15.15.dylib` and try again? http://dl.dropbox.com/u/22242495/temp/libpng15.15.dylib

thanks!

**Comment by arturadib** [comment] 2012-04-10 21:19
PS: at this point I'm just trying to see if that's the only thing breaking the tests; I'll still need to change the reference path inside QtGui when deploying the bundled lib.

**Comment by yayscripting** [comment] 2012-04-11 13:00
After adding libpng it works fine! This was the only thing that was breaking your system.

``` bash
$ node make test
_________________________________________________________________
Running Node-Qt tests

rm: no such file or directory: img-test/*

Running test file qcolor.js
Running test file qfont.js
Running test file qimage.js
Running test file qmatrix.js
path.existsSync is deprecated. It is now called `fs.existsSync`.
! regression warning: img-test/ dir does not exist. creating it...
Running test file qpainter.js
path.existsSync is deprecated. It is now called `fs.existsSync`.
!!! image regression in test: painter-drawtext-saved-black
!!! image regression in test: painter-drawtext-hello-black
!!! image regression in test: painter-drawtext-hello-green
Running test file qpainterpath.js
path.existsSync is deprecated. It is now called `fs.existsSync`.
Running test file qpen.js
path.existsSync is deprecated. It is now called `fs.existsSync`.
Running test file qpixmap.js
path.existsSync is deprecated. It is now called `fs.existsSync`.
Running test file qpointf.js
path.existsSync is deprecated. It is now called `fs.existsSync`.
Running test file qscrollarea.js
Running test file qsound.js
path.existsSync is deprecated. It is now called `fs.existsSync`.
Running test file qwidget.js
```

**Comment by alessioalex** [comment] 2012-04-11 19:33
I guess I have the same problem: https://github.com/arturadib/node-qt/issues/8

**Comment by raphaelhuefner** [comment] 2012-04-13 18:43
Putting the libpng in place enabled me to run the example from README.md. No luck with the tests, though.

```
rh:~/projects/node/native-qt$ uname -a
Darwin rh.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386
rh:~/projects/node/native-qt$ node --version
v0.6.15
rh:~/projects/node/native-qt$ npm --version
1.1.16
rh:~/projects/node/native-qt$ gcc --version
i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5664)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rh:~/projects/node/native-qt$ python --version
Python 2.6.1
```

**Comment by arturadib** [comment] 2012-04-13 19:52
@raphaelhuefner that's odd. can you please provide the error output during the test runs?

**Comment by raphaelhuefner** [comment] 2012-04-13 20:37
Beware, I'm running node 0.6.15 ... so as I understand the output is not as revealing as it could be with 0.7.x:

```
rh:~/projects/node/native-qt$ node make test

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module '/Users/raphael/projects/node/native-qt/make'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
rh:~/projects/node/native-qt$ 
```

Could you point me to some documentation how to run 0.6 and 0.7 side-by-side on a Mac? I tried googling that, but don't seem to use proper keywords.

Or tell me which other command's output you need to see...

**Comment by arturadib** [comment] 2012-04-13 20:55
@raphaelhuefner the problem doesn't seem to be related to the native addon -- node can't seem to find `make.js`. can you please check it's in there?

**Comment by arturadib** [comment] 2012-04-13 20:57
I've pushed a new version that comes with `libpng` bundled.

@yayscripting can you please try it again? you should be able to remove the libpng file you downloaded, and run:

```
$ npm install git://github.com/arturadib/node-qt.git
```

to get the latest development version.

**Comment by raphaelhuefner** [comment] 2012-04-13 21:01
Doh! ... I better check I'm there. ;-) 

```
rh:~/projects/node/native-qt$ cd node_modules/node-qt/
rh:~/projects/node/native-qt/node_modules/node-qt$ find . -name "make.js"
./make.js
./node_modules/shelljs/make.js
rh:~/projects/node/native-qt/node_modules/node-qt$ node make test
_________________________________________________________________
Running Node-Qt tests

rm: no such file or directory: img-test/*

Running test file qcolor.js
Running test file qfont.js
Running test file qimage.js
Running test file qmatrix.js
! regression warning: img-test/ dir does not exist. creating it...
Running test file qpainter.js
!!! image regression in test: painter-drawtext-saved-black
!!! image regression in test: painter-drawtext-hello-black
!!! image regression in test: painter-drawtext-hello-green
Running test file qpainterpath.js
Running test file qpen.js
Running test file qpixmap.js
Running test file qpointf.js
Running test file qscrollarea.js
Running test file qsound.js
Running test file qwidget.js
rh:~/projects/node/native-qt/node_modules/node-qt$ node make test
_________________________________________________________________
Running Node-Qt tests

Running test file qcolor.js
Running test file qfont.js
Running test file qimage.js
Running test file qmatrix.js
Running test file qpainter.js
!!! image regression in test: painter-drawtext-saved-black
!!! image regression in test: painter-drawtext-hello-black
!!! image regression in test: painter-drawtext-hello-green
Running test file qpainterpath.js
Running test file qpen.js
Running test file qpixmap.js
Running test file qpointf.js
Running test file qscrollarea.js
Running test file qsound.js
Running test file qwidget.js
rh:~/projects/node/native-qt/node_modules/node-qt$ 
```

I ran the tests twice b/c of that "img-test/*" warning.

**Comment by raphaelhuefner** [comment] 2012-04-13 21:14
Works now! Awesome! ;-)

```
rh:~/projects/node/native-qt$ sudo rm /usr/X11/lib/libpng15.15.dylib
Password:
rh:~/projects/node/native-qt$ rm -rf node_modules/
rh:~/projects/node/native-qt$ npm install git://github.com/arturadib/node-qt.git
npm http GET https://registry.npmjs.org/shelljs/0.0.5pre4
npm http 304 https://registry.npmjs.org/shelljs/0.0.5pre4

> node-qt@0.0.2 install /Users/raphael/projects/node/native-qt/node_modules/node-qt
> node-gyp rebuild

info it worked if it ends with ok 
spawn python [ '/Users/raphael/.node-gyp/0.6.15/tools/gyp_addon',
  'binding.gyp',
  '-I/Users/raphael/projects/node/native-qt/node_modules/node-qt/build/config.gypi',
  '-f',
  'make' ]
spawn make [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/qt/src/qt.o
  CXX(target) Release/obj.target/qt/src/QtCore/qsize.o
  CXX(target) Release/obj.target/qt/src/QtCore/qpointf.o
  CXX(target) Release/obj.target/qt/src/QtGui/qapplication.o
  CXX(target) Release/obj.target/qt/src/QtGui/qwidget.o
  CXX(target) Release/obj.target/qt/src/QtGui/qmouseevent.o
  CXX(target) Release/obj.target/qt/src/QtGui/qkeyevent.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpixmap.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpainter.o
  CXX(target) Release/obj.target/qt/src/QtGui/qcolor.o
  CXX(target) Release/obj.target/qt/src/QtGui/qbrush.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpen.o
  CXX(target) Release/obj.target/qt/src/QtGui/qimage.o
  CXX(target) Release/obj.target/qt/src/QtGui/qpainterpath.o
  CXX(target) Release/obj.target/qt/src/QtGui/qfont.o
  CXX(target) Release/obj.target/qt/src/QtGui/qmatrix.o
  CXX(target) Release/obj.target/qt/src/QtGui/qsound.o
  CXX(target) Release/obj.target/qt/src/QtGui/qscrollarea.o
  CXX(target) Release/obj.target/qt/src/QtGui/qscrollbar.o
  CXX(target) Release/obj.target/qt/src/QtTest/qtesteventlist.o
  SOLINK_MODULE(target) Release/qt.node
  SOLINK_MODULE(target) Release/qt.node: Finished
info done ok 
node-qt@0.0.2 ./node_modules/node-qt
└── shelljs@0.0.5pre4
rh:~/projects/node/native-qt$ cd node_modules/node-qt/
rh:~/projects/node/native-qt/node_modules/node-qt$ node make test
_________________________________________________________________
Running Node-Qt tests

rm: no such file or directory: img-test/*

Running test file qcolor.js
Running test file qfont.js
Running test file qimage.js
Running test file qmatrix.js
! regression warning: img-test/ dir does not exist. creating it...
Running test file qpainter.js
!!! image regression in test: painter-drawtext-saved-black
!!! image regression in test: painter-drawtext-hello-black
!!! image regression in test: painter-drawtext-hello-green
Running test file qpainterpath.js
Running test file qpen.js
Running test file qpixmap.js
Running test file qpointf.js
Running test file qscrollarea.js
Running test file qsound.js
Running test file qwidget.js
rh:~/projects/node/native-qt/node_modules/node-qt$ cd ..
rh:~/projects/node/native-qt/node_modules$ cd ..
rh:~/projects/node/native-qt$ node helloworld.js 
```

**Comment by arturadib** [comment] 2012-04-13 21:17
Superb, closing. Please reopen if it creeps up again.

**Closed as completed** 2012-04-13 21:17 UTC
Labels: mac, bug
